baseURL = "http://ailopez-entaina.github.com/"
languageCode = "es"
title = "GuardPass"
theme = "tale"

[params]
  css = ["./scss/styles.css"]
   background_color_class = "bg-black"
   favicon = "/images/favicon.png"
[menu]
  [[menu.main]]
    identifier = "contact"
    name = "Contacto"
    title = "Contacto"
    url = "/contact/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0