baseURL = "http://ailopez-entaina.github.com/"
languageCode = "es"
title = "GuardPass"
theme = "tale"

[params]
  css = ["scss/styles.css"]
   background_color_class = "bg-black"
   favicon = "images/favicon.ico"
